### ISSUE TITLE
[Suggestion] Hide coordinates in tooltips of linked glasses

### ISSUE THREAD

**Issue by Alessandro404** [StarChasers/OCGlasses#62]
Hi!

I'm playing a modpack that tries to hide world coordinates from the player. As OC already hides those numbers, I was hoping for a config to do the same thing with the glasses.

(oh, and the dimension too!)

Thank you

**Comment by ben-mkiv** [comment]
next release will hide the coords when gamerule `reducedDebugInfo` is set to true

**Comment by ben-mkiv** [comment]
heres a prebuild of 2.1.0 which has a new tooltip for the glasses, you should turn off absolute render positions in the openglasses mod config if you dont want any absolute related features (otherwise getUserPosition() would report the absolute player position if the terminal is set to absolute rendering)

https://github.com/StarChasers/OCGlasses/releases/tag/inb4release

new tooltip layout
![](https://i.imgur.com/EmnkqsX.png)

However, they expose the distance to the terminal in the GUI
![](https://i.imgur.com/MF4plYz.png)

**Comment by ben-mkiv** [comment]
2.1.1 is on curseForge now (which includes the changes)
https://minecraft.curseforge.com/projects/openglasses2/files/2729855
