### ISSUE TITLE
[Bug] Incompatible with Immersive Vehicles

### ISSUE THREAD

**Issue by nrllewellyn** [StarChasers/OCGlasses#77]
**Describe the bug**
Installing OCGlasses prevents Immersive Vehicles' controls screen form displaying.

**In which environment did the Bug appear?**
Single Player and Dedicated Server

**To Reproduce**
1. Install OCGlasses and Immersive Vehicles
2. Try to open the Open Vehicles controls screen

**Expected behavior**
Controls screen should open

**Screenshots / Code Snippet**
N/A

**Minecraft:**
 - OpenGlasses-MC1.12.2-2.2-36
- OpenComputers-MC1.12.2-1.7.4.153
- Immersive+Vehicles-1.12.2-15.3.0
 - Minecraft 1.12
 - Forge 14.23.5.2847

**Additional context**
Bug will be cross-posted to Immersive Vehicle's Github, and I will post a link shortly.

**Comment by nrllewellyn** [comment]
Issue in Immersive Vehicle's Github: https://github.com/DonBruce64/MinecraftTransportSimulator/issues/199

**Comment by nrllewellyn** [comment]
Note: This appears to be an issue with the way one of the mods does keybindings, as with both mods installed the keybinding for Immersive Vehicles controls is labeled as "Glasses Config" in the controls menu.

**Comment by nrllewellyn** [comment]
With OCGlasses installed:
![2019-10-13_02 43 27](https://user-images.githubusercontent.com/4811061/66711944-5085c500-ed63-11e9-8cf0-9a7d3a414ff9.png)

**Comment by nrllewellyn** [comment]
Without OCGlasses installed:
![2019-10-13_02 45 08](https://user-images.githubusercontent.com/4811061/66711962-9478ca00-ed63-11e9-932a-0bfdcfef530f.png)

**Comment by ben-mkiv** [comment]
both mods, screwed up their translation keys.

**Comment by DonBruce64** [comment]
Yup, that's a bad on my end.  I have the lang file set to "key.config", so that explains why it would conflict with your mod.  I swore I got everything converted to use my modID as a prefix in the lang file after I had conflicts with block names, but I guess I missed the controls.  Still shouldn't keep the user from opening the config, though, as the binding has a separate category.  He should see two "Config Glasses" sections, one under MTS and one under OCG.  Unless Forge's keybindings don't care about category and only care about the binding name....

Currently in the process of re-writing my mod for less pain to update to 1.14.4, so I won't be able to get to this for a while.  Will let you know when I do.

**Comment by ben-mkiv** [comment]
I've uploaded a fixed version of OpenGlasses (2.2-38) to Curse/Twitch

**Comment by DonBruce64** [comment]
Should close the loop and say V15.4.0 of my mod has corrected this on my end as well.
